---

- name: "{{ site.name }} | Create root data directory"
  file:
    path: "{{ site.data_dir | dirname }}"
    state: "directory"
    owner: "root"
    group: "root"
    mode: "0755"

- name: "{{ site.name }} | Create container data directory"
  file:
    path: "{{ site.data_dir }}"
    state: "directory"
    owner: "www-data"
    group: "root"
    mode: "0755"
